### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by SkettenCode** [scrumProjectOrg/taskmaster#5]
- [ ] Überschrift mit mehreren Unterpunkten im stil von diesem Github projekt
- [ ] kurze Beschreibung der Software
- [ ] Hinweis zum anmelden wenn noch nicht erfolgt
- [ ] Wenn angemeldet Weiterleitung oder Hinweis zur eigenen Seite

**Comment by proelio57** [comment]
Kein Framework, da Features dieser nicht benötigt werden und nur HTML, CSS und ein wenig JavaScript verwendet werden sollen.

**Comment by proelio57** [comment]
moved to issue #7

**Comment by SkettenCode** [comment]
13 Stunden
