### ISSUE TITLE
Rudimentary HTML + CSS programming of the sketch from #6

### ISSUE THREAD

**Issue by proelio57** [scrumProjectOrg/taskmaster#7]
Writing some dank HTML and CSS based on the sketch from issue #6

**Comment by HLennart** [comment]
check [our templates](https://github.com/scrumProjectOrg/taskmaster/tree/main/templates) for existing html documents. It already contains a (mostly empty) page for the home site.

If you want data from the backend server, check out the [Django template language](https://docs.djangoproject.com/en/3.1/ref/templates/language/l).

**Comment by proelio57** [comment]
ca. 8 hours needed for this

**Comment by SkettenCode** [comment]
8 Stunden
